title: "Luzes do Abismo"
description: "Análises técnicas sobre avistamentos de OVNIs no Brasil e América do Sul"
baseurl: ""
url: "https://MaxxxxmusRJ.github.io"

# Force rebuild
updated: 2025-06-02

# Posts configuration
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true

# Build settings
future: true

author:
  name: "Luzes POA"
  email: "maxximus.meridius@gmail.com"
  youtube: "https://www.youtube.com/@LuzesAbismo"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

timezone: America/Sao_Paulo

# Custom CSS
minima:
  skin: dark
  
# Override CSS
sass:
  style: compressed

